// src/components/charts/chart-bar.vue
<template>
    <div>
        <svg ref="svg"
            :width="width"
            :height="height"
            :style="chartStyle"
        >
        </svg>
    </div>
</template>
<script>
import * as d3 from 'd3';
import _ from 'lodash';
export default {
    name: 'chart-bar',
    // 外部传进来的参数
    props: {
        chartStyle: {
            type: Object,
            default: function () {
                return {}
            }
        },
        data: {
            type: Array,
            default: function () {
                return [];
            }
        },
        keys: {
            type: Array,
            default: function () {
                return ['apples', 'bananas', 'cherries', 'dates'];
            }
        }
    },
    computed: {
        width: function () {
            return parseInt(this.chartStyle.width, 10) || 360
        },
        height: function () {
            return parseInt(this.chartStyle.height, 10) || 240
        }
    },
    // 监听data变化， 有变化就更新图表
    watch: {
        data: function (newData) {
            console.log('更新图表')
            // 
            initChart(this.$refs.svg, newData, this.keys);
        }
    },
    // 此时已经渲染到页面，可以拿到svg ，渲染无数据的图表
    mounted () {
        initChart(this.$refs.svg, this.data, this.keys);
    }
}

/**
 * 渲染柱图
 * @param {Element} svg element 
 * @param {Array}
 * @param {String}
 * 这里是普通的写法，把data, x, y 坐标的单位等可抽离的数据通过传参的方式传进来
 */
const initChart = function ($svg, data, keys) {
    var series = d3.stack()
        .keys(keys)
        .offset(d3.stackOffsetDiverging)(data);

    var svg = d3.select($svg),
        margin = {top: 20, right: 30, bottom: 30, left: 60},
        width = +svg.attr("width"),
        height = +svg.attr("height");

    var x = d3.scaleBand()
        .domain(data.map(function(d) { return d.month; }))
        .rangeRound([margin.left, width - margin.right])
        .padding(0.1);

    var y = d3.scaleLinear()
        .domain([d3.min(series, stackMin), d3.max(series, stackMax)])
        .rangeRound([height - margin.bottom, margin.top]);

    var z = d3.scaleOrdinal(d3.schemeCategory10);

    svg.append("g")
        .selectAll("g")
        .data(series)
        .enter()
            .append("g")
            .attr("fill", function(d) { return z(d.key); })
            .selectAll("rect")
            .data(function(d) { return d; })
            .enter()
                .append("rect")
                .attr("width", x.bandwidth)
                .attr("x", function(d) { return x(d.data.month); })
                .attr("y", function(d) { return y(d[1]); })
                .attr("height", function(d) { return y(d[0]) - y(d[1]); })

    svg.append("g")
        .attr("transform", "translate(0," + (y(0) || 1) + ")")
        .call(d3.axisBottom(x));

    svg.append("g")
        .attr("transform", "translate(" + margin.left + ",0)")
        .call(d3.axisLeft(y));

    function stackMin(serie) {
    return d3.min(serie, function(d) { return d[0]; });
    }

    function stackMax(serie) {
    return d3.max(serie, function(d) { return d[1]; });
    }


}

</script>
<style>

</style>

// src/components/charts/chart-bar.jsx
import * as React from 'react';
import PropTypes from 'prop-types';
import * as d3 from 'd3';
import _ from 'lodash';
export default class ChartLine extends React.Component {
    static defaultProps = {
        data: [],
        style: {},
        chartStyle: {},
    };
    static propsTypes = {
        style: PropTypes.object,
        chartStyle: PropTypes.object,
        option: PropTypes.object
    }

    componentWillReceiveProps (nextProps) {
        if (nextProps.option) {
            var option = _.merge(defaultOption, nextProps.option);
            initChart(this.refs.svg, option);
        }
    }

    componentDidMount () {
        var option = Object.assign({}, defaultOption);
        initChart(this.refs.svg, option);
    }
    render() {
        var {style, chartStyle} = this.props;
        var width = parseInt(style.width, 10) || 260;
        var height = parseInt(style.height, 10) || 140;
        return (
            <div style={style}>
                <svg ref="svg"
                    width={width}
                    height={height}
                    style={chartStyle}
                >
                </svg>
            </div>
        )
    }
}


var defaultOption = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : [],
            axisTick: {
                alignWithLabel: true
            },
            axisLine:{
                lineStyle: {
                    color: '#FFF'
                }
            }
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLine:{
                lineStyle: {
                    color: '#FFF'
                }
            }
        }
    ],
    series : [
    ]
};

/**
 * 渲染柱图
 * @param {Element} svg element 
 */
const initChart = function (container, option) {
    const svg = d3.select(container);
    const height = svg.attr('height');
    // eslint-disable-next-line
    const width = svg.attr('width');

	const g = svg.append('g')
				.attr('transform','translate(50,50)');

	let data = [];
	//使用map
    // for(var i=0;i<series[0].data.length;i++){
    // 	data[i] = new Map();
    // 	for(var j=0;j<series.length;j++){
    // 		data[i].set(series[j]['name'],series[j].data[i])
    // 	}
    // }

    //Object
    if (option.series.length !== 0) {
        for(let i=0;i<option.series[0].data.length;i++){
            data[i] = {};
            for(let j=0;j<option.series.length;j++){
                if (option.series[j] === undefined) {
                    data[i] = [];
                    continue;
                }
                data[i][option.series[j]['name']] = option.series[j].data[i];
            }
            data[i]['year'] = `200${i}`;
        }
    }
    	
    var stackKeys = option.series.map(item => item.name)
    let stack = d3.stack().keys(stackKeys);
    let aSeries = stack(data);

    let xDate = [];
    for(let i of data){
    	xDate.push(i.year);
    }
    let xScale = d3.scaleBand()
                    .domain(xDate)
                    
    				.range([0,height])
    				.padding(0.5);
    
    let yMax = d3.max(aSeries[aSeries.length-1] || 0,(d) => d[1])

    let yScale = d3.scaleLinear()
                    .domain([0,yMax])
    				.range([height,0]);

    //drawBar
    let g_stack = g.append('g').classed('stackBar',true);

    for(let i=0;i<aSeries.length;i++){
	     g_stack.selectAll('ract')
	     .data(aSeries[i])
	     .enter()
	     .append('rect')
	     .attr('x',(d,i) => xScale(xDate[i]) )
	     .attr('y',(d,i) => yScale(d[1]) )
	     .attr('width',xScale.bandwidth())
	     .attr('height',(d,i) => height - yScale(d[1] - d[0]) )
	     .attr('fill', d3.schemeCategory10[i])
    }

    // eslint-disable-next-line
    const xAxis = g.append('g').classed('xAxis',true)
            .attr('transform', `translate(0,${height - 10})`)
            .attr('stroke', option.xAxis[0].axisLine.lineStyle.color)
            .call(d3.axisBottom(xScale));
    // eslint-disable-next-line
    const yAxis = g.append('g').classed('yAxis',true)
            .attr('stroke', option.yAxis[0].axisLine.lineStyle.color)
    		.call(d3.axisLeft(yScale));
}
