// src/components/loading/Loading.vue
<template>
    <div class="loading-container">
        <div class="outside-circle">
            <div class="inside-circle">
                
            </div>
        </div>
        <p class="circle-text">
            <span class="text"></span>
        </p>
    </div>
</template>
<script>
 
 export default {
     name: 'loading'
 }
</script>
<style>
@import './index.css';
</style>

// src/components/loading/index.jsx
import * as React from 'react';
import './index.css';
const Loading = () => {
    return (
        <div className="loading-container">
            <div className="outside-circle">
                <div className="inside-circle">
                    
                </div>
            </div>
            <p className="circle-text">
                <span className="text"></span>
            </p>
        </div>
    )
}
export default Loading;
