// src/App.jsx
import * as React from 'react';
import AppRouter from './router';
import store from './store';
// 各种Provider
import { Provider } from 'react-redux';

import './static/css/base.css';
import './static/css/app.css';
import './static/css/common.css';
import './static/css/cover.less';
// use $store every where

class App extends React.Component{
  render() {
    return (
        <Provider store={store}>
            <AppRouter/>
        </Provider>
    );
  }
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>
export default {
    name: 'app'
};
</script>

<style lang="less">
@import './assets/css/base.css';
@import './assets/css/app.css';
@import './assets/css/common.css';
@import './assets/css/cover.less';
</style>
